{% set name = "xcube-4d-viewer" %}
{% set version = "1.0.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xcube_4d_viewer-{{ version }}.tar.gz
  sha256: 9d717d09d6eb5e043ad9bd5506e8e45cefa10335ce032c9af7076096d95a94fe

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - xcube

test:
  imports:
    - xcube_4d_viewer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/xcube-4d-viewer/
  summary: API extension to the xcube server allowing cubes to be visualised in the Earthwave 4D viewer.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - juliabizon
    - earthwave-admin
