{% set name = "xcube-4d-viewer" %}
{% set version = "1.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xcube_4d_viewer-{{ version }}.tar.gz
  sha256: 87bdae5442749466d266fb88c1ea0bade52eeb222d5f345d63877d1a35782d3b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - xcube

test:
  imports:
    - xcube_4d_viewer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/xcube-4d-viewer/
  summary: API extension to the xcube server allowing cubes to be visualised in the Earthwave 4D viewer.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - juliabizon
    - earthwave-admin
